export interface SeedTeam {
  name: string;
  shortName: string;
  league: string;
  country: string;
  starRating: number;
  overallRating: number;
  attackRating: number;
  midfieldRating: number;
  defenseRating: number;
  primaryPlaystyle: string;
  secondaryPlaystyle?: string;
  rivalryTags?: string[];
  keyPlayers: string;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  badgeTier?: string;
}

export const INITIAL_TEAMS_DATA: SeedTeam[] = [
  // --- PREMIER LEAGUE ---
  {
    name: 'Manchester City',
    shortName: 'MCI',
    league: 'Premier League',
    country: 'England',
    starRating: 5.0,
    overallRating: 86,
    attackRating: 88,
    midfieldRating: 86,
    defenseRating: 85,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['Manchester Derby', 'Title Contenders'],
    keyPlayers: 'Haaland, De Bruyne, Rodri, Foden',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
    badgeTier: 'META',
  },
  {
    name: 'Arsenal',
    shortName: 'ARS',
    league: 'Premier League',
    country: 'England',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 85,
    midfieldRating: 85,
    defenseRating: 86,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['North London Derby', 'Title Contenders'],
    keyPlayers: 'Saka, Saliba, Ødegaard, Rice',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
    primaryColor: '#EF0107',
    secondaryColor: '#063672',
    badgeTier: 'META',
  },
  {
    name: 'Liverpool',
    shortName: 'LIV',
    league: 'Premier League',
    country: 'England',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 87,
    midfieldRating: 84,
    defenseRating: 84,
    primaryPlaystyle: 'Gegenpress',
    secondaryPlaystyle: 'Fast Break',
    rivalryTags: ['North West Derby', 'Merseyside Derby'],
    keyPlayers: 'Salah, Van Dijk, Alexander-Arnold, Alisson',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
    badgeTier: 'META',
  },
  {
    name: 'Chelsea',
    shortName: 'CHE',
    league: 'Premier League',
    country: 'England',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 83,
    midfieldRating: 82,
    defenseRating: 81,
    primaryPlaystyle: 'Fast Break',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['London Derby'],
    keyPlayers: 'Palmer, Enzo Fernández, Caicedo, Jackson',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
    primaryColor: '#034694',
    secondaryColor: '#DBA111',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    league: 'Premier League',
    country: 'England',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 83,
    midfieldRating: 81,
    defenseRating: 81,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Counter Attack',
    rivalryTags: ['North London Derby'],
    keyPlayers: 'Son Heung-min, Maddison, Romero, Solanke',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Manchester United',
    shortName: 'MUN',
    league: 'Premier League',
    country: 'England',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 82,
    midfieldRating: 82,
    defenseRating: 81,
    primaryPlaystyle: 'Counter Attack',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Manchester Derby', 'North West Derby'],
    keyPlayers: 'Bruno Fernandes, Rashford, Mainoo, Martínez',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
    primaryColor: '#DA291C',
    secondaryColor: '#FBE122',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Aston Villa',
    shortName: 'AVL',
    league: 'Premier League',
    country: 'England',
    starRating: 4.5,
    overallRating: 81,
    attackRating: 83,
    midfieldRating: 81,
    defenseRating: 80,
    primaryPlaystyle: 'Gegenpress',
    secondaryPlaystyle: 'High Offside Line',
    rivalryTags: ['Midlands Clash'],
    keyPlayers: 'Watkins, Tielemans, McGinn, Dibu Martínez',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_crest_%282016%29.svg',
    primaryColor: '#95BFE5',
    secondaryColor: '#670E36',
    badgeTier: 'DARK_HORSE',
  },
  {
    name: 'Newcastle United',
    shortName: 'NEW',
    league: 'Premier League',
    country: 'England',
    starRating: 4.5,
    overallRating: 81,
    attackRating: 82,
    midfieldRating: 82,
    defenseRating: 80,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Direct Play',
    rivalryTags: ['Tyne-Wear Derby'],
    keyPlayers: 'Isak, Bruno Guimarães, Gordon, Tonali',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
    primaryColor: '#241F20',
    secondaryColor: '#F2A900',
    badgeTier: 'DARK_HORSE',
  },

  // --- LA LIGA ---
  {
    name: 'Real Madrid',
    shortName: 'RMA',
    league: 'La Liga',
    country: 'Spain',
    starRating: 5.0,
    overallRating: 87,
    attackRating: 89,
    midfieldRating: 87,
    defenseRating: 85,
    primaryPlaystyle: 'Counter Attack',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['El Clásico', 'Madrid Derby'],
    keyPlayers: 'Mbappé, Vinícius Jr, Bellingham, Valverde',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
    primaryColor: '#FEBE10',
    secondaryColor: '#00529F',
    badgeTier: 'META',
  },
  {
    name: 'FC Barcelona',
    shortName: 'BAR',
    league: 'La Liga',
    country: 'Spain',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 86,
    midfieldRating: 85,
    defenseRating: 84,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['El Clásico', 'Catalan Derby'],
    keyPlayers: 'Lamine Yamal, Lewandowski, Pedri, Gavi',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
    primaryColor: '#A50044',
    secondaryColor: '#004D98',
    badgeTier: 'META',
  },
  {
    name: 'Atlético Madrid',
    shortName: 'ATM',
    league: 'La Liga',
    country: 'Spain',
    starRating: 4.5,
    overallRating: 83,
    attackRating: 84,
    midfieldRating: 83,
    defenseRating: 84,
    primaryPlaystyle: 'Park The Bus',
    secondaryPlaystyle: 'Counter Attack',
    rivalryTags: ['Madrid Derby'],
    keyPlayers: 'Griezmann, Julián Álvarez, De Paul, Oblak',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg',
    primaryColor: '#CB3524',
    secondaryColor: '#272E61',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Athletic Club',
    shortName: 'ATH',
    league: 'La Liga',
    country: 'Spain',
    starRating: 4.0,
    overallRating: 80,
    attackRating: 81,
    midfieldRating: 79,
    defenseRating: 80,
    primaryPlaystyle: 'Wing Play',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['Basque Derby'],
    keyPlayers: 'Nico Williams, Iñaki Williams, Sancet, Simón',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/73/Athletic_Club_logo.svg',
    primaryColor: '#EE2524',
    secondaryColor: '#000000',
    badgeTier: 'MID_TIER',
  },
  {
    name: 'Real Sociedad',
    shortName: 'RSO',
    league: 'La Liga',
    country: 'Spain',
    starRating: 4.0,
    overallRating: 80,
    attackRating: 79,
    midfieldRating: 81,
    defenseRating: 79,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'Gegenpress',
    rivalryTags: ['Basque Derby'],
    keyPlayers: 'Kubo, Oyarzabal, Zubimendi, Remiro',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg',
    primaryColor: '#005CA5',
    secondaryColor: '#FFFFFF',
    badgeTier: 'MID_TIER',
  },

  // --- BUNDESLIGA ---
  {
    name: 'Bayern Munich',
    shortName: 'BAY',
    league: 'Bundesliga',
    country: 'Germany',
    starRating: 5.0,
    overallRating: 86,
    attackRating: 88,
    midfieldRating: 85,
    defenseRating: 84,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Der Klassiker'],
    keyPlayers: 'Harry Kane, Musiala, Sané, Kimmich',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg',
    primaryColor: '#DC052D',
    secondaryColor: '#0066B2',
    badgeTier: 'META',
  },
  {
    name: 'Bayer Leverkusen',
    shortName: 'B04',
    league: 'Bundesliga',
    country: 'Germany',
    starRating: 4.5,
    overallRating: 84,
    attackRating: 85,
    midfieldRating: 85,
    defenseRating: 83,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'Gegenpress',
    rivalryTags: ['Rhine Derby'],
    keyPlayers: 'Florian Wirtz, Grimaldo, Frimpong, Xhaka',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg',
    primaryColor: '#E32219',
    secondaryColor: '#000000',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    league: 'Bundesliga',
    country: 'Germany',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 83,
    midfieldRating: 82,
    defenseRating: 81,
    primaryPlaystyle: 'Fast Break',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['Der Klassiker', 'Revierderby'],
    keyPlayers: 'Brandt, Guirassy, Adeyemi, Kobel',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'RB Leipzig',
    shortName: 'RBL',
    league: 'Bundesliga',
    country: 'Germany',
    starRating: 4.0,
    overallRating: 81,
    attackRating: 82,
    midfieldRating: 80,
    defenseRating: 80,
    primaryPlaystyle: 'Gegenpress',
    secondaryPlaystyle: 'Fast Break',
    rivalryTags: ['East Germany Clash'],
    keyPlayers: 'Openda, Xavi Simons, Šeško, Gulácsi',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',
    primaryColor: '#DD013F',
    secondaryColor: '#041E42',
    badgeTier: 'DARK_HORSE',
  },

  // --- SERIE A ---
  {
    name: 'Inter Milan',
    shortName: 'INT',
    league: 'Serie A',
    country: 'Italy',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 86,
    midfieldRating: 86,
    defenseRating: 84,
    primaryPlaystyle: 'Wing Play',
    secondaryPlaystyle: 'Counter Attack',
    rivalryTags: ['Derby della Madonnina', 'Derby d\'Italia'],
    keyPlayers: 'Lautaro Martínez, Barella, Calhanoglu, Dimarco',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',
    primaryColor: '#0066B2',
    secondaryColor: '#000000',
    badgeTier: 'META',
  },
  {
    name: 'AC Milan',
    shortName: 'ACM',
    league: 'Serie A',
    country: 'Italy',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 84,
    midfieldRating: 81,
    defenseRating: 82,
    primaryPlaystyle: 'Fast Break',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Derby della Madonnina'],
    keyPlayers: 'Rafael Leão, Theo Hernández, Pulisic, Maignan',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
    primaryColor: '#FB090B',
    secondaryColor: '#000000',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Juventus',
    shortName: 'JUV',
    league: 'Serie A',
    country: 'Italy',
    starRating: 4.5,
    overallRating: 82,
    attackRating: 82,
    midfieldRating: 81,
    defenseRating: 83,
    primaryPlaystyle: 'Park The Bus',
    secondaryPlaystyle: 'Counter Attack',
    rivalryTags: ['Derby d\'Italia', 'Turin Derby'],
    keyPlayers: 'Vlahović, Yildiz, Bremer, Koopmeiners',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Juventus_FC_-_Logo_2017.svg',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Atalanta',
    shortName: 'ATA',
    league: 'Serie A',
    country: 'Italy',
    starRating: 4.0,
    overallRating: 81,
    attackRating: 82,
    midfieldRating: 81,
    defenseRating: 79,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Man-Marking Press',
    rivalryTags: ['Lombardy Derby'],
    keyPlayers: 'Lookman, De Ketelaere, Scalvini, Ederson',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/66/AtalantaBC.svg',
    primaryColor: '#1E71B8',
    secondaryColor: '#000000',
    badgeTier: 'DARK_HORSE',
  },
  {
    name: 'AS Roma',
    shortName: 'ASR',
    league: 'Serie A',
    country: 'Italy',
    starRating: 4.0,
    overallRating: 80,
    attackRating: 81,
    midfieldRating: 80,
    defenseRating: 79,
    primaryPlaystyle: 'Counter Attack',
    secondaryPlaystyle: 'Long Ball',
    rivalryTags: ['Derby della Capitale'],
    keyPlayers: 'Dybala, Dovbyk, Pellegrini, Svilar',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
    primaryColor: '#8E1F2F',
    secondaryColor: '#F0BC42',
    badgeTier: 'MID_TIER',
  },

  // --- LIGUE 1 ---
  {
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    league: 'Ligue 1',
    country: 'France',
    starRating: 5.0,
    overallRating: 84,
    attackRating: 85,
    midfieldRating: 84,
    defenseRating: 83,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Le Classique'],
    keyPlayers: 'Dembélé, Barcola, Vitinha, Marquinhos',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
    primaryColor: '#002F6C',
    secondaryColor: '#DA291C',
    badgeTier: 'META',
  },
  {
    name: 'AS Monaco',
    shortName: 'ASM',
    league: 'Ligue 1',
    country: 'France',
    starRating: 4.0,
    overallRating: 79,
    attackRating: 80,
    midfieldRating: 79,
    defenseRating: 78,
    primaryPlaystyle: 'Fast Break',
    secondaryPlaystyle: 'Gegenpress',
    rivalryTags: ['Cote d\'Azur Derby'],
    keyPlayers: 'Minamino, Akliouche, Zakaria, Embolo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/ba/AS_Monaco_FC.svg',
    primaryColor: '#E41B13',
    secondaryColor: '#FFFFFF',
    badgeTier: 'MID_TIER',
  },
  {
    name: 'Olympique Marseille',
    shortName: 'OM',
    league: 'Ligue 1',
    country: 'France',
    starRating: 4.0,
    overallRating: 79,
    attackRating: 81,
    midfieldRating: 78,
    defenseRating: 77,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Le Classique'],
    keyPlayers: 'Greenwood, Højbjerg, Wahi, Rulli',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',
    primaryColor: '#00A3E0',
    secondaryColor: '#FFFFFF',
    badgeTier: 'MID_TIER',
  },

  // --- SAUDI PRO LEAGUE & MLS ---
  {
    name: 'Al-Nassr',
    shortName: 'NAS',
    league: 'Saudi Pro League',
    country: 'Saudi Arabia',
    starRating: 4.0,
    overallRating: 79,
    attackRating: 84,
    midfieldRating: 78,
    defenseRating: 75,
    primaryPlaystyle: 'Counter Attack',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Riyadh Derby'],
    keyPlayers: 'Cristiano Ronaldo, Sadio Mané, Brozović, Laporte',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Al_Nassr_FC.svg',
    primaryColor: '#FFF200',
    secondaryColor: '#00529F',
    badgeTier: 'DARK_HORSE',
  },
  {
    name: 'Al-Hilal',
    shortName: 'HIL',
    league: 'Saudi Pro League',
    country: 'Saudi Arabia',
    starRating: 4.5,
    overallRating: 81,
    attackRating: 83,
    midfieldRating: 81,
    defenseRating: 79,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['Riyadh Derby', 'Saudi Classico'],
    keyPlayers: 'Neymar Jr, Mitrović, Rúben Neves, Cancelo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Al_Hilal_SFC_Logo.svg',
    primaryColor: '#00529F',
    secondaryColor: '#FFFFFF',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Inter Miami CF',
    shortName: 'MIA',
    league: 'MLS',
    country: 'USA',
    starRating: 4.0,
    overallRating: 78,
    attackRating: 84,
    midfieldRating: 79,
    defenseRating: 72,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'Tiki-Taka',
    rivalryTags: ['Florida Derby'],
    keyPlayers: 'Lionel Messi, Luis Suárez, Sergio Busquets, Jordi Alba',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Inter_Miami_CF_logo.svg',
    primaryColor: '#F7B5CD',
    secondaryColor: '#231F20',
    badgeTier: 'DARK_HORSE',
  },

  // --- INTERNATIONAL TEAMS ---
  {
    name: 'France',
    shortName: 'FRA',
    league: 'International',
    country: 'France',
    starRating: 5.0,
    overallRating: 86,
    attackRating: 88,
    midfieldRating: 85,
    defenseRating: 85,
    primaryPlaystyle: 'Fast Break',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['World Cup Finalists', 'European Giant'],
    keyPlayers: 'Mbappé, Griezmann, Tchouaméni, Saliba',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/France_national_football_team_seal.svg',
    primaryColor: '#002342',
    secondaryColor: '#FFFFFF',
    badgeTier: 'META',
  },
  {
    name: 'England',
    shortName: 'ENG',
    league: 'International',
    country: 'England',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 87,
    midfieldRating: 86,
    defenseRating: 84,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'Wing Play',
    rivalryTags: ['Auld Enemy Derby', 'European Giant'],
    keyPlayers: 'Harry Kane, Bellingham, Saka, Foden',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/England_crest.svg',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
    badgeTier: 'META',
  },
  {
    name: 'Spain',
    shortName: 'ESP',
    league: 'International',
    country: 'Spain',
    starRating: 5.0,
    overallRating: 86,
    attackRating: 86,
    midfieldRating: 87,
    defenseRating: 84,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['European Champions', 'Iberian Derby'],
    keyPlayers: 'Lamine Yamal, Rodri, Nico Williams, Dani Olmo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/31/Spain_National_Football_Team_Badge.svg',
    primaryColor: '#AA1523',
    secondaryColor: '#F1BF00',
    badgeTier: 'META',
  },
  {
    name: 'Argentina',
    shortName: 'ARG',
    league: 'International',
    country: 'Argentina',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 87,
    midfieldRating: 85,
    defenseRating: 84,
    primaryPlaystyle: 'Gegenpress',
    secondaryPlaystyle: 'Counter Attack',
    rivalryTags: ['World Champions', 'Superclásico de las Américas'],
    keyPlayers: 'Lionel Messi, Lautaro Martínez, Julián Álvarez, Mac Allister',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d1/Argentine_Football_Association_logo.svg',
    primaryColor: '#75AADB',
    secondaryColor: '#FFFFFF',
    badgeTier: 'META',
  },
  {
    name: 'Brazil',
    shortName: 'BRA',
    league: 'International',
    country: 'Brazil',
    starRating: 5.0,
    overallRating: 85,
    attackRating: 87,
    midfieldRating: 84,
    defenseRating: 84,
    primaryPlaystyle: 'Wing Play',
    secondaryPlaystyle: 'Joga Bonito',
    rivalryTags: ['Superclásico de las Américas'],
    keyPlayers: 'Vinícius Jr, Rodrygo, Endrick, Marquinhos',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/99/Brazilian_Football_Confederation_logo.svg',
    primaryColor: '#FFDC02',
    secondaryColor: '#009B3A',
    badgeTier: 'META',
  },
  {
    name: 'Portugal',
    shortName: 'POR',
    league: 'International',
    country: 'Portugal',
    starRating: 4.5,
    overallRating: 84,
    attackRating: 85,
    midfieldRating: 85,
    defenseRating: 83,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'Fast Break',
    rivalryTags: ['Iberian Derby'],
    keyPlayers: 'Cristiano Ronaldo, Bruno Fernandes, Bernardo Silva, Rúben Dias',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Portuguese_Football_Federation.svg',
    primaryColor: '#E42518',
    secondaryColor: '#006600',
    badgeTier: 'TOP_TIER',
  },
  {
    name: 'Germany',
    shortName: 'GER',
    league: 'International',
    country: 'Germany',
    starRating: 4.5,
    overallRating: 84,
    attackRating: 84,
    midfieldRating: 85,
    defenseRating: 83,
    primaryPlaystyle: 'Gegenpress',
    secondaryPlaystyle: 'Tiki-Taka',
    rivalryTags: ['European Giant'],
    keyPlayers: 'Musiala, Wirtz, Havertz, Rüdiger',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e3/DFB-Team_logo.svg',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
    badgeTier: 'TOP_TIER',
  },

  // --- UNDERDOG TEAMS ---
  {
    name: 'Girona FC',
    shortName: 'GIR',
    league: 'La Liga',
    country: 'Spain',
    starRating: 3.5,
    overallRating: 77,
    attackRating: 77,
    midfieldRating: 77,
    defenseRating: 76,
    primaryPlaystyle: 'Tiki-Taka',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['Catalan Derby'],
    keyPlayers: 'Tsygankov, Abel Ruiz, Yangel Herrera',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/90/Girona_FC_Logo.svg',
    primaryColor: '#ED1C24',
    secondaryColor: '#FFFFFF',
    badgeTier: 'UNDERDOG',
  },
  {
    name: 'Brighton & Hove Albion',
    shortName: 'BHA',
    league: 'Premier League',
    country: 'England',
    starRating: 3.5,
    overallRating: 78,
    attackRating: 79,
    midfieldRating: 78,
    defenseRating: 76,
    primaryPlaystyle: 'Possession',
    secondaryPlaystyle: 'High Press',
    rivalryTags: ['M23 Derby'],
    keyPlayers: 'Mitoma, João Pedro, Ferguson, Dunk',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg',
    primaryColor: '#0057B8',
    secondaryColor: '#FFFFFF',
    badgeTier: 'UNDERDOG',
  },
  {
    name: 'Bologna FC',
    shortName: 'BOL',
    league: 'Serie A',
    country: 'Italy',
    starRating: 3.5,
    overallRating: 77,
    attackRating: 76,
    midfieldRating: 77,
    defenseRating: 77,
    primaryPlaystyle: 'High Press',
    secondaryPlaystyle: 'Fast Break',
    rivalryTags: ['Emilia Derby'],
    keyPlayers: 'Orsolini, Castro, Ferguson, Beukema',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5b/Bologna_fc_logo.svg',
    primaryColor: '#1A2C56',
    secondaryColor: '#A81C26',
    badgeTier: 'UNDERDOG',
  },
];
